/* automatically generated by rust-bindgen 0.58.1 */

extern "C" {
    pub fn decompress_rpak(
        a1: *mut ::std::os::raw::c_longlong,
        a2: ::std::os::raw::c_ulonglong,
        a3: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_char;
}
extern "C" {
    pub fn get_decompressed_size(
        aparams: *mut ::std::os::raw::c_longlong,
        file_buf: *mut u8,
        some_magic_shit: ::std::os::raw::c_longlong,
        file_size: ::std::os::raw::c_longlong,
        off_without_header_qm: ::std::os::raw::c_longlong,
        header_size: ::std::os::raw::c_longlong,
    ) -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn hash_string(a1: *mut ::std::os::raw::c_uint) -> ::std::os::raw::c_ulonglong;
}
